on:
  push:
    branches:
    - main

name: main
jobs:

  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run project
      run: |
        dotnet build
        cd project
        dotnet run
